// <auto-generated />
using System;
using FinanceiraXPTO.Dados.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinanceiraXPTO.Dados.Migrations
{
    [DbContext(typeof(FinanceiraXPTOContext))]
    partial class FinanceiraXPTOContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinanceiraXPTO.Dominio.Entidades.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CPF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroCelular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UF")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cliente");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CPF = "46243366073",
                            NomeCliente = "José Silva",
                            NumeroCelular = "21999999999",
                            UF = "PR"
                        },
                        new
                        {
                            Id = 2,
                            CPF = "67696022024",
                            NomeCliente = "André Silva",
                            NumeroCelular = "21999999998",
                            UF = "SP"
                        },
                        new
                        {
                            Id = 3,
                            CPF = "48635067088",
                            NomeCliente = "Antonio Silva",
                            NumeroCelular = "21999999997",
                            UF = "SP"
                        },
                        new
                        {
                            Id = 4,
                            CPF = "88789122046",
                            NomeCliente = "Carlos Silva",
                            NumeroCelular = "21999999996",
                            UF = "RJ"
                        },
                        new
                        {
                            Id = 5,
                            CPF = "88789122047",
                            NomeCliente = "Carlos Silva",
                            NumeroCelular = "21999999996",
                            UF = "BA"
                        },
                        new
                        {
                            Id = 6,
                            CPF = "88789122048",
                            NomeCliente = "Carlos Silva",
                            NumeroCelular = "21999999996",
                            UF = "SE"
                        },
                        new
                        {
                            Id = 7,
                            CPF = "88789122049",
                            NomeCliente = "Carlos Silva",
                            NumeroCelular = "21999999996",
                            UF = "PR"
                        },
                        new
                        {
                            Id = 8,
                            CPF = "88789122040",
                            NomeCliente = "Carlos Silva",
                            NumeroCelular = "21999999996",
                            UF = "RS"
                        },
                        new
                        {
                            Id = 9,
                            CPF = "88789122041",
                            NomeCliente = "Carlos Silva",
                            NumeroCelular = "21999999996",
                            UF = "SP"
                        },
                        new
                        {
                            Id = 10,
                            CPF = "88789122042",
                            NomeCliente = "Carlos Silva",
                            NumeroCelular = "21999999996",
                            UF = "ES"
                        });
                });

            modelBuilder.Entity("FinanceiraXPTO.Dominio.Entidades.Financiamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataUltimoVencimento")
                        .HasColumnType("datetime2");

                    b.Property<int>("TipoFinanciamento")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Financiamento");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CPF = "46243366073",
                            ClienteId = 1,
                            DataUltimoVencimento = new DateTime(2023, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TipoFinanciamento = 0,
                            ValorTotal = 20000m
                        },
                        new
                        {
                            Id = 2,
                            CPF = "67696022024",
                            ClienteId = 2,
                            DataUltimoVencimento = new DateTime(2023, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TipoFinanciamento = 1,
                            ValorTotal = 10000m
                        },
                        new
                        {
                            Id = 3,
                            CPF = "67696022024",
                            ClienteId = 2,
                            DataUltimoVencimento = new DateTime(2023, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TipoFinanciamento = 0,
                            ValorTotal = 5000m
                        },
                        new
                        {
                            Id = 4,
                            CPF = "48635067088",
                            ClienteId = 3,
                            DataUltimoVencimento = new DateTime(2023, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TipoFinanciamento = 0,
                            ValorTotal = 75000m
                        },
                        new
                        {
                            Id = 5,
                            CPF = "88789122046",
                            ClienteId = 4,
                            DataUltimoVencimento = new DateTime(2023, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TipoFinanciamento = 1,
                            ValorTotal = 3000m
                        },
                        new
                        {
                            Id = 6,
                            CPF = "88789122046",
                            ClienteId = 4,
                            DataUltimoVencimento = new DateTime(2023, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TipoFinanciamento = 1,
                            ValorTotal = 2000m
                        },
                        new
                        {
                            Id = 7,
                            CPF = "88789122047",
                            ClienteId = 5,
                            DataUltimoVencimento = new DateTime(2023, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TipoFinanciamento = 1,
                            ValorTotal = 2000m
                        },
                        new
                        {
                            Id = 8,
                            CPF = "88789122048",
                            ClienteId = 6,
                            DataUltimoVencimento = new DateTime(2023, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TipoFinanciamento = 0,
                            ValorTotal = 1000m
                        },
                        new
                        {
                            Id = 9,
                            CPF = "88789122049",
                            ClienteId = 7,
                            DataUltimoVencimento = new DateTime(2023, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TipoFinanciamento = 0,
                            ValorTotal = 6000m
                        },
                        new
                        {
                            Id = 10,
                            CPF = "88789122041",
                            ClienteId = 8,
                            DataUltimoVencimento = new DateTime(2023, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TipoFinanciamento = 1,
                            ValorTotal = 8000m
                        },
                        new
                        {
                            Id = 11,
                            CPF = "88789122042",
                            ClienteId = 9,
                            DataUltimoVencimento = new DateTime(2023, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TipoFinanciamento = 1,
                            ValorTotal = 1500m
                        });
                });

            modelBuilder.Entity("FinanceiraXPTO.Dominio.Entidades.Parcela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("datetime2");

                    b.Property<int>("FinanciamentoId")
                        .HasColumnType("int");

                    b.Property<int>("NumeroParcela")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorParcela")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FinanciamentoId");

                    b.ToTable("Parcelas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataPagamento = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataVencimento = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 1,
                            NumeroParcela = 1,
                            ValorParcela = 4000m
                        },
                        new
                        {
                            Id = 2,
                            DataPagamento = new DateTime(2023, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataVencimento = new DateTime(2023, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 1,
                            NumeroParcela = 2,
                            ValorParcela = 4000m
                        },
                        new
                        {
                            Id = 3,
                            DataPagamento = new DateTime(2023, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataVencimento = new DateTime(2023, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 1,
                            NumeroParcela = 3,
                            ValorParcela = 4000m
                        },
                        new
                        {
                            Id = 4,
                            DataPagamento = new DateTime(2023, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataVencimento = new DateTime(2023, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 1,
                            NumeroParcela = 4,
                            ValorParcela = 4000m
                        },
                        new
                        {
                            Id = 5,
                            DataVencimento = new DateTime(2023, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 1,
                            NumeroParcela = 5,
                            ValorParcela = 4000m
                        },
                        new
                        {
                            Id = 6,
                            DataPagamento = new DateTime(2022, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataVencimento = new DateTime(2022, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 2,
                            NumeroParcela = 1,
                            ValorParcela = 1000m
                        },
                        new
                        {
                            Id = 7,
                            DataPagamento = new DateTime(2022, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataVencimento = new DateTime(2022, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 2,
                            NumeroParcela = 2,
                            ValorParcela = 1000m
                        },
                        new
                        {
                            Id = 8,
                            DataPagamento = new DateTime(2022, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataVencimento = new DateTime(2022, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 2,
                            NumeroParcela = 3,
                            ValorParcela = 1000m
                        },
                        new
                        {
                            Id = 9,
                            DataPagamento = new DateTime(2022, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataVencimento = new DateTime(2022, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 2,
                            NumeroParcela = 4,
                            ValorParcela = 1000m
                        },
                        new
                        {
                            Id = 10,
                            DataPagamento = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataVencimento = new DateTime(2023, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 2,
                            NumeroParcela = 5,
                            ValorParcela = 1000m
                        },
                        new
                        {
                            Id = 11,
                            DataPagamento = new DateTime(2023, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataVencimento = new DateTime(2023, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 2,
                            NumeroParcela = 6,
                            ValorParcela = 1000m
                        },
                        new
                        {
                            Id = 12,
                            DataPagamento = new DateTime(2023, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataVencimento = new DateTime(2023, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 2,
                            NumeroParcela = 7,
                            ValorParcela = 1000m
                        },
                        new
                        {
                            Id = 13,
                            DataPagamento = new DateTime(2023, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataVencimento = new DateTime(2023, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 2,
                            NumeroParcela = 8,
                            ValorParcela = 1000m
                        },
                        new
                        {
                            Id = 14,
                            DataPagamento = new DateTime(2023, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataVencimento = new DateTime(2023, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 2,
                            NumeroParcela = 9,
                            ValorParcela = 1000m
                        },
                        new
                        {
                            Id = 15,
                            DataVencimento = new DateTime(2023, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 2,
                            NumeroParcela = 10,
                            ValorParcela = 1000m
                        },
                        new
                        {
                            Id = 16,
                            DataPagamento = new DateTime(2022, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataVencimento = new DateTime(2022, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 3,
                            NumeroParcela = 1,
                            ValorParcela = 1250m
                        },
                        new
                        {
                            Id = 17,
                            DataPagamento = new DateTime(2022, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataVencimento = new DateTime(2022, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 3,
                            NumeroParcela = 2,
                            ValorParcela = 1250m
                        },
                        new
                        {
                            Id = 18,
                            DataPagamento = new DateTime(2022, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataVencimento = new DateTime(2022, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 3,
                            NumeroParcela = 3,
                            ValorParcela = 1250m
                        },
                        new
                        {
                            Id = 19,
                            DataPagamento = new DateTime(2022, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataVencimento = new DateTime(2022, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 3,
                            NumeroParcela = 4,
                            ValorParcela = 1250m
                        },
                        new
                        {
                            Id = 20,
                            DataPagamento = new DateTime(2023, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataVencimento = new DateTime(2023, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 4,
                            NumeroParcela = 1,
                            ValorParcela = 15000m
                        },
                        new
                        {
                            Id = 21,
                            DataPagamento = new DateTime(2023, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataVencimento = new DateTime(2023, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 4,
                            NumeroParcela = 2,
                            ValorParcela = 15000m
                        },
                        new
                        {
                            Id = 22,
                            DataPagamento = new DateTime(2023, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataVencimento = new DateTime(2023, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 4,
                            NumeroParcela = 3,
                            ValorParcela = 15000m
                        },
                        new
                        {
                            Id = 23,
                            DataPagamento = new DateTime(2023, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataVencimento = new DateTime(2023, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 4,
                            NumeroParcela = 4,
                            ValorParcela = 15000m
                        },
                        new
                        {
                            Id = 24,
                            DataVencimento = new DateTime(2023, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 4,
                            NumeroParcela = 5,
                            ValorParcela = 15000m
                        },
                        new
                        {
                            Id = 25,
                            DataPagamento = new DateTime(2023, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataVencimento = new DateTime(2023, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 5,
                            NumeroParcela = 1,
                            ValorParcela = 600m
                        },
                        new
                        {
                            Id = 26,
                            DataPagamento = new DateTime(2023, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataVencimento = new DateTime(2023, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 5,
                            NumeroParcela = 2,
                            ValorParcela = 600m
                        },
                        new
                        {
                            Id = 27,
                            DataPagamento = new DateTime(2023, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataVencimento = new DateTime(2023, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 5,
                            NumeroParcela = 3,
                            ValorParcela = 600m
                        },
                        new
                        {
                            Id = 28,
                            DataPagamento = new DateTime(2023, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataVencimento = new DateTime(2023, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 5,
                            NumeroParcela = 4,
                            ValorParcela = 600m
                        },
                        new
                        {
                            Id = 29,
                            DataPagamento = new DateTime(2023, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataVencimento = new DateTime(2023, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 5,
                            NumeroParcela = 5,
                            ValorParcela = 600m
                        },
                        new
                        {
                            Id = 30,
                            DataPagamento = new DateTime(2023, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataVencimento = new DateTime(2023, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 6,
                            NumeroParcela = 1,
                            ValorParcela = 400m
                        },
                        new
                        {
                            Id = 31,
                            DataPagamento = new DateTime(2023, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataVencimento = new DateTime(2023, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 6,
                            NumeroParcela = 2,
                            ValorParcela = 400m
                        },
                        new
                        {
                            Id = 32,
                            DataPagamento = new DateTime(2023, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataVencimento = new DateTime(2023, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 6,
                            NumeroParcela = 3,
                            ValorParcela = 400m
                        },
                        new
                        {
                            Id = 33,
                            DataPagamento = new DateTime(2023, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataVencimento = new DateTime(2023, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 6,
                            NumeroParcela = 4,
                            ValorParcela = 400m
                        },
                        new
                        {
                            Id = 34,
                            DataVencimento = new DateTime(2023, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 6,
                            NumeroParcela = 5,
                            ValorParcela = 400m
                        },
                        new
                        {
                            Id = 35,
                            DataPagamento = new DateTime(2023, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataVencimento = new DateTime(2023, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 6,
                            NumeroParcela = 1,
                            ValorParcela = 400m
                        },
                        new
                        {
                            Id = 36,
                            DataPagamento = new DateTime(2023, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataVencimento = new DateTime(2023, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 6,
                            NumeroParcela = 2,
                            ValorParcela = 400m
                        },
                        new
                        {
                            Id = 37,
                            DataPagamento = new DateTime(2023, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataVencimento = new DateTime(2023, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 6,
                            NumeroParcela = 3,
                            ValorParcela = 400m
                        },
                        new
                        {
                            Id = 38,
                            DataPagamento = new DateTime(2023, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataVencimento = new DateTime(2023, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 6,
                            NumeroParcela = 4,
                            ValorParcela = 400m
                        },
                        new
                        {
                            Id = 39,
                            DataVencimento = new DateTime(2023, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 6,
                            NumeroParcela = 5,
                            ValorParcela = 400m
                        },
                        new
                        {
                            Id = 40,
                            DataPagamento = new DateTime(2023, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataVencimento = new DateTime(2023, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 7,
                            NumeroParcela = 1,
                            ValorParcela = 500m
                        },
                        new
                        {
                            Id = 41,
                            DataVencimento = new DateTime(2023, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 7,
                            NumeroParcela = 2,
                            ValorParcela = 500m
                        },
                        new
                        {
                            Id = 42,
                            DataVencimento = new DateTime(2023, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 7,
                            NumeroParcela = 3,
                            ValorParcela = 500m
                        },
                        new
                        {
                            Id = 43,
                            DataVencimento = new DateTime(2023, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 7,
                            NumeroParcela = 4,
                            ValorParcela = 500m
                        },
                        new
                        {
                            Id = 44,
                            DataPagamento = new DateTime(2023, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataVencimento = new DateTime(2023, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 8,
                            NumeroParcela = 1,
                            ValorParcela = 250m
                        },
                        new
                        {
                            Id = 45,
                            DataPagamento = new DateTime(2023, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataVencimento = new DateTime(2023, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 8,
                            NumeroParcela = 2,
                            ValorParcela = 250m
                        },
                        new
                        {
                            Id = 46,
                            DataVencimento = new DateTime(2023, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 8,
                            NumeroParcela = 3,
                            ValorParcela = 250m
                        },
                        new
                        {
                            Id = 47,
                            DataVencimento = new DateTime(2023, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 8,
                            NumeroParcela = 4,
                            ValorParcela = 250m
                        },
                        new
                        {
                            Id = 48,
                            DataPagamento = new DateTime(2023, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataVencimento = new DateTime(2023, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 9,
                            NumeroParcela = 1,
                            ValorParcela = 3000m
                        },
                        new
                        {
                            Id = 49,
                            DataVencimento = new DateTime(2023, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 9,
                            NumeroParcela = 2,
                            ValorParcela = 3000m
                        },
                        new
                        {
                            Id = 50,
                            DataPagamento = new DateTime(2023, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataVencimento = new DateTime(2023, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 10,
                            NumeroParcela = 1,
                            ValorParcela = 1600m
                        },
                        new
                        {
                            Id = 51,
                            DataPagamento = new DateTime(2023, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataVencimento = new DateTime(2023, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 10,
                            NumeroParcela = 2,
                            ValorParcela = 1600m
                        },
                        new
                        {
                            Id = 52,
                            DataPagamento = new DateTime(2023, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataVencimento = new DateTime(2023, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 10,
                            NumeroParcela = 3,
                            ValorParcela = 1600m
                        },
                        new
                        {
                            Id = 53,
                            DataVencimento = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 10,
                            NumeroParcela = 4,
                            ValorParcela = 1600m
                        },
                        new
                        {
                            Id = 54,
                            DataVencimento = new DateTime(2023, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 10,
                            NumeroParcela = 5,
                            ValorParcela = 1600m
                        },
                        new
                        {
                            Id = 55,
                            DataPagamento = new DateTime(2023, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataVencimento = new DateTime(2023, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 11,
                            NumeroParcela = 1,
                            ValorParcela = 750m
                        },
                        new
                        {
                            Id = 56,
                            DataPagamento = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataVencimento = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanciamentoId = 11,
                            NumeroParcela = 2,
                            ValorParcela = 750m
                        });
                });

            modelBuilder.Entity("FinanceiraXPTO.Dominio.Entidades.Financiamento", b =>
                {
                    b.HasOne("FinanceiraXPTO.Dominio.Entidades.Cliente", "Cliente")
                        .WithMany("Financiamentos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("FinanceiraXPTO.Dominio.Entidades.Parcela", b =>
                {
                    b.HasOne("FinanceiraXPTO.Dominio.Entidades.Financiamento", "Financiamento")
                        .WithMany("Parcelas")
                        .HasForeignKey("FinanciamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Financiamento");
                });

            modelBuilder.Entity("FinanceiraXPTO.Dominio.Entidades.Cliente", b =>
                {
                    b.Navigation("Financiamentos");
                });

            modelBuilder.Entity("FinanceiraXPTO.Dominio.Entidades.Financiamento", b =>
                {
                    b.Navigation("Parcelas");
                });
#pragma warning restore 612, 618
        }
    }
}
